### ISSUE TITLE
Part 1 feedback

### ISSUE THREAD

**Issue by andreashandel** [epid8060fall2019/JonathanWilson_Project#1]
There data description doesn't contain enough information for me to judge if this is a feasible/good project. I'm concerned by the fact that you say the data is still being compiled. For the next part of this project due in a few weeks, you will have to present first analyses, so you need to get all data together rather quickly. If that's not possible you might change to a project involving readily available data.

**Comment by JJWilson1991** [comment]
I'll figure something else out from existing data over the weekend and update my project. The data collection isn't as far a long as I had hoped at this stage.

**Comment by JJWilson1991** [comment]
I've come up with a different project and uploaded the data
