### ISSUE TITLE
code not working

### ISSUE THREAD

**Issue by andreashandel** [epid8060fall2019/JonathanWilson_Project#2]
I'm not able to reproduce your project since your code tries to load data from a path that doesn't exist on my computer. please update all paths to relative, so it works independent of a specific the computer setup. once updated, i'll try again.

**Comment by JJWilson1991** [comment]
Sorry about that, overlooked it, I think it should work now.

**Comment by andreashandel** [comment]
Thanks. the processing script works now, but the exploratory script aborts with an error message.

**Comment by JJWilson1991** [comment]
When is the error occurring? at the beginning or later on? i'm not coming across any now

**Comment by andreashandel** [comment]
tried again, worked now.
